import os
import json
from datetime import datetime, timezone
from typing import Tuple, Dict, Any
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app.db.models import Incident, Report, EvidenceFile, AuditLog, AnalystNote, IncidentEvent, Alert, IndicatorOfCompromise
from app.core.config import settings

def ensure_report_dir():
    os.makedirs(settings.REPORT_STORAGE_DIR, exist_ok=True)

class ReportGenerator:
    @staticmethod
    def generate_incident_report(db: Session, incident_id: str, analyst_name: str = "Automated Analyst") -> Tuple[str, str]:
        ensure_report_dir()
        incident = db.query(Incident).filter(Incident.id == incident_id).first()
        if not incident:
            raise ValueError("Incident not found.")

        timestamp_str = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        pdf_filename = f"Incident_Report_{incident.id[:8]}_{timestamp_str}.pdf"
        json_filename = f"Incident_Report_{incident.id[:8]}_{timestamp_str}.json"
        
        pdf_path = os.path.join(settings.REPORT_STORAGE_DIR, pdf_filename)
        json_path = os.path.join(settings.REPORT_STORAGE_DIR, json_filename)

        # Gather related data
        events = [assoc.event for assoc in incident.event_associations if assoc.event]
        alerts = [assoc.alert for assoc in incident.event_associations if assoc.alert]
        notes = incident.notes

        evidence_files = db.query(EvidenceFile).all()
        audit_logs = db.query(AuditLog).filter(
            AuditLog.target_id == incident.id
        ).order_by(AuditLog.timestamp.desc()).all()

        # 1. Build JSON report
        json_data = {
            "platform": "TraceForensics DFIR Platform",
            "report_generated_at": datetime.now(timezone.utc).isoformat(),
            "generated_by": analyst_name,
            "incident": {
                "id": incident.id,
                "title": incident.title,
                "status": incident.status,
                "severity": incident.severity,
                "created_at": incident.created_at.isoformat(),
                "updated_at": incident.updated_at.isoformat(),
                "description": incident.description,
                "resolution_notes": incident.resolution_notes
            },
            "alerts": [
                {
                    "alert_id": a.id,
                    "rule_code": a.rule.rule_code if a.rule else "N/A",
                    "rule_name": a.rule.name if a.rule else "N/A",
                    "severity": a.severity,
                    "confidence": a.confidence,
                    "trigger_reason": a.trigger_reason,
                    "timestamp": a.timestamp.isoformat()
                } for a in alerts
            ],
            "timeline_events": [
                {
                    "event_id": e.id,
                    "timestamp": e.timestamp.isoformat(),
                    "hostname": e.hostname,
                    "username": e.username,
                    "event_type": e.event_type,
                    "event_description": e.event_description,
                    "process_name": e.process_name,
                    "auth_result": e.auth_result
                } for e in sorted(events, key=lambda x: x.timestamp)
            ],
            "evidence_integrity": [
                {
                    "filename": f.filename,
                    "sha256_hash": f.sha256_hash,
                    "line_count": f.line_count,
                    "acquisition_time": f.acquisition_time.isoformat()
                } for f in evidence_files
            ],
            "analyst_notes": [
                {
                    "author": n.analyst.username if n.analyst else "Analyst",
                    "timestamp": n.created_at.isoformat(),
                    "content": n.content
                } for n in notes
            ],
            "disclaimer": "This report is generated by TraceForensics rule-based detection engine and analyst documentation. Hash verification and log entries alone do not constitute tamper-proof legal chain of custody."
        }

        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(json_data, f, indent=2)

        # 2. Build PDF report using ReportLab
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom palette
        primary_color = colors.HexColor('#0F172A')   # Navy
        accent_color = colors.HexColor('#2563EB')    # Blue
        critical_color = colors.HexColor('#DC2626')  # Red
        text_dark = colors.HexColor('#1E293B')
        bg_light = colors.HexColor('#F8FAFC')

        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=20,
            leading=24,
            textColor=primary_color,
            spaceAfter=6
        )
        
        subtitle_style = ParagraphStyle(
            'SubTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            textColor=accent_color,
            spaceAfter=12
        )

        section_heading = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=16,
            textColor=primary_color,
            spaceBefore=14,
            spaceAfter=6
        )

        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=text_dark
        )

        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Italic'],
            fontName='Helvetica-Oblique',
            fontSize=8,
            leading=11,
            textColor=colors.HexColor('#64748B')
        )

        elements = []

        # Header Title
        elements.append(Paragraph("TRACEFORENSICS — INCIDENT INVESTIGATION REPORT", title_style))
        elements.append(Paragraph(f"CONFIDENTIAL // AUTOMATED DFIR PLATFORM REPORT // GENERATED: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=accent_color, spaceAfter=12))

        # Incident Summary Metadata Table
        meta_data = [
            [Paragraph("<b>Incident Title:</b>", body_style), Paragraph(incident.title, body_style)],
            [Paragraph("<b>Incident ID:</b>", body_style), Paragraph(incident.id, body_style)],
            [Paragraph("<b>Status:</b>", body_style), Paragraph(f"<font color='{accent_color.hexval()}'><b>{incident.status}</b></font>", body_style)],
            [Paragraph("<b>Severity:</b>", body_style), Paragraph(f"<font color='{critical_color.hexval()}'><b>{incident.severity}</b></font>", body_style)],
            [Paragraph("<b>Created At:</b>", body_style), Paragraph(incident.created_at.strftime("%Y-%m-%d %H:%M:%S UTC"), body_style)],
            [Paragraph("<b>Lead Analyst:</b>", body_style), Paragraph(analyst_name, body_style)]
        ]

        t_meta = Table(meta_data, colWidths=[1.5*inch, 5.5*inch])
        t_meta.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), bg_light),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        elements.append(t_meta)
        elements.append(Spacer(1, 10))

        # Executive Summary
        elements.append(Paragraph("1. Executive Summary & Overview", section_heading))
        elements.append(Paragraph(incident.description, body_style))
        if incident.resolution_notes:
            elements.append(Spacer(1, 4))
            elements.append(Paragraph(f"<b>Resolution Notes:</b> {incident.resolution_notes}", body_style))
        elements.append(Spacer(1, 10))

        # Rule Detections & Alerts
        elements.append(Paragraph("2. Triggered Detection Rules & Security Alerts", section_heading))
        if alerts:
            alert_table_data = [["Rule Code", "Rule Name", "Severity", "Trigger Reason"]]
            for a in alerts:
                rule_code = a.rule.rule_code if a.rule else "RULE-X"
                rule_name = a.rule.name if a.rule else "Custom Alert"
                alert_table_data.append([
                    Paragraph(f"<b>{rule_code}</b>", body_style),
                    Paragraph(rule_name, body_style),
                    Paragraph(f"<b>{a.severity}</b>", body_style),
                    Paragraph(a.trigger_reason, body_style)
                ])
            t_alerts = Table(alert_table_data, colWidths=[1.1*inch, 2.0*inch, 0.9*inch, 3.0*inch])
            t_alerts.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), primary_color),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
                ('PADDING', (0,0), (-1,-1), 4),
            ]))
            # Fix header text style for white background
            for i in range(4):
                alert_table_data[0][i] = Paragraph(f"<font color='white'><b>{alert_table_data[0][i]}</b></font>", body_style)
            elements.append(t_alerts)
        else:
            elements.append(Paragraph("No automated alerts associated with this incident.", body_style))
        elements.append(Spacer(1, 10))

        # Chronological Event Timeline
        elements.append(Paragraph("3. Chronological Incident Event Timeline", section_heading))
        if events:
            timeline_data = [["Timestamp (UTC)", "Host", "User", "Event Type", "Description"]]
            for ev in sorted(events, key=lambda x: x.timestamp)[:15]:  # Top 15 key events
                timeline_data.append([
                    Paragraph(ev.timestamp.strftime("%Y-%m-%d %H:%M:%S"), body_style),
                    Paragraph(ev.hostname or "-", body_style),
                    Paragraph(ev.username or "-", body_style),
                    Paragraph(ev.event_type, body_style),
                    Paragraph((ev.event_description or "")[:80], body_style)
                ])
            t_timeline = Table(timeline_data, colWidths=[1.3*inch, 1.1*inch, 1.1*inch, 1.2*inch, 2.3*inch])
            t_timeline.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E293B')),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
                ('PADDING', (0,0), (-1,-1), 4),
            ]))
            for i in range(5):
                timeline_data[0][i] = Paragraph(f"<font color='white'><b>{timeline_data[0][i]}</b></font>", body_style)
            elements.append(t_timeline)
        else:
            elements.append(Paragraph("No raw event records currently attached to this timeline.", body_style))
        elements.append(Spacer(1, 10))

        # Evidence Hash Integrity & Chain of Custody
        elements.append(Paragraph("4. Evidence Integrity & Cryptographic Checksums (SHA-256)", section_heading))
        if evidence_files:
            ev_data = [["Filename", "SHA-256 Checksum", "Acquisition Time"]]
            for ef in evidence_files:
                ev_data.append([
                    Paragraph(ef.filename, body_style),
                    Paragraph(f"<font size=7><code>{ef.sha256_hash}</code></font>", body_style),
                    Paragraph(ef.acquisition_time.strftime("%Y-%m-%d %H:%M:%S UTC"), body_style)
                ])
            t_ev = Table(ev_data, colWidths=[1.8*inch, 3.7*inch, 1.5*inch])
            t_ev.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0F172A')),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
                ('PADDING', (0,0), (-1,-1), 4),
            ]))
            for i in range(3):
                ev_data[0][i] = Paragraph(f"<font color='white'><b>{ev_data[0][i]}</b></font>", body_style)
            elements.append(t_ev)
        elements.append(Spacer(1, 10))

        # Analyst Notes
        elements.append(Paragraph("5. Analyst Notes & Conclusions", section_heading))
        if notes:
            for n in notes:
                author = n.analyst.username if n.analyst else "Analyst"
                elements.append(Paragraph(f"<b>[{n.created_at.strftime('%Y-%m-%d %H:%M')}] {author}:</b> {n.content}", body_style))
                elements.append(Spacer(1, 3))
        else:
            elements.append(Paragraph("No analyst notes recorded yet.", body_style))
        elements.append(Spacer(1, 14))

        # Legal Disclaimer
        elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=8))
        elements.append(Paragraph(
            "<b>LEGAL DISCLAIMER & LIMITATIONS:</b> This document was generated automatically by TraceForensics Automated DFIR Platform. "
            "Rule-based detections identify suspicious activity patterns but do not conclusively prove malicious intent or compromise. "
            "SHA-256 evidence hashing and local audit logs demonstrate integrity within this application framework but do not constitute "
            "a legally certified, tamper-proof chain of custody required for judicial proceedings.",
            disclaimer_style
        ))

        doc.build(elements)

        return pdf_path, json_path
